name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action-no-cache:
    name: GitHub Actions Test (no cache)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          block: latest
          rpc-endpoints-json: '{"mainnet":"http://127.0.0.1:8545"}'
          cache-key-prefix: foundry-cache-boost-ci-no-cache-${{ github.sha }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action ("new" run)
        id: test-action
        uses: ./
        with:
          block: 24735604
          rpc-endpoints-json: '{"mainnet":"https://eth.meowrpc.com"}'
          cache-key-prefix: foundry-cache-boost-ci-mainnet

      - name: Mock Foundry Cache ("previous" run)
        id: mock-cache
        run: |
          mkdir -p ~/.foundry/cache/rpc/mainnet
          echo << EOF > ~/.foundry/cache/rpc/mainnet/24735602
          {
            "storage": {
              "0xbb256c2f1b677e27118b0345fd2b3894d2e6d487": {
                "0x8": "0x100000930020331891ebc5365190e79876812e91e000000d0f542b16972d95b",
                "0x2": "0x1d6c694252e187e53f577bdb00ccb0ce1",
                "0x0": "0x100003300330000ffffdc0000000000000000ff8be44946ea45710f061d92",
                "0x1": "0xf9eb2201cbc83ae306a3757b6debba3",
                "0x63187d71e139eee983a88d0737447c7451979b3dbb75903c76b5fe430d36588e": "0x9000004000000000000000000000000000000000000000000000000000000000",
                "0x54cdd369e4e8a8515e52ca72ec816c2101831ad1f18bf44102ed171459c9b4f8": "0x6f",
                "0x9": "0x10000093001d8df5b11ba3b5a757aaef54d14336f000000d363039569156ddf",
                "0x4": "0x2a24e4e1d"
              }
            }
          }
          EOF
